import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";
import ProtectedRoute from "@/components/ProtectedRoute/ProtectedRoute";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          toastOptions={{
            success: {
              style: {
                background: "linear-gradient(135deg, #69995D, #394648)",
                padding: "12px 24px",
                color: "#F8E9E9",
                borderRadius: "12px",
                boxShadow: "0 4px 15px rgba(0, 0, 0, 0.2)",
                fontFamily: "'Poppins', sans-serif",
                fontWeight: "600",
                fontSize: "14px",
                border: "1px solid rgba(255, 255, 255, 0.1)",
                animation: "fadeIn 0.5s ease-in-out",
              },
              iconTheme: {
                primary: "#F8E9E9",
                secondary: "#69995D",
              },
            },
            error: {
              style: {
                background: "linear-gradient(135deg, #EDB6A3, #CBAC88)",
                padding: "12px 24px",
                color: "#394648",
                borderRadius: "12px",
                boxShadow: "0 4px 15px rgba(0, 0, 0, 0.2)",
                fontFamily: "'Poppins', sans-serif",
                fontWeight: "600",
                fontSize: "14px",
                border: "1px solid rgba(255, 255, 255, 0.1)",
                animation: "fadeIn 0.5s ease-in-out",
              },
              iconTheme: {
                primary: "#394648",
                secondary: "#EDB6A3",
              },
            },
            loading: {
              style: {
                background: "linear-gradient(135deg, #CBAC88, #EDB6A3)",
                padding: "12px 24px",
                color: "#394648",
                borderRadius: "12px",
                boxShadow: "0 4px 15px rgba(0, 0, 0, 0.2)",
                fontFamily: "'Poppins', sans-serif",
                fontWeight: "600",
                fontSize: "14px",
                border: "1px solid rgba(255, 255, 255, 0.1)",
                display: "flex",
                alignItems: "center",
                gap: "8px",
              },
              iconTheme: {
                primary: "#394648",
                secondary: "#CBAC88",
              },
            },
          }}
        />
        <ReduxProvider>
          <ProtectedRoute>
            {children}
            </ProtectedRoute>
        </ReduxProvider>
      </body>
    </html>
  );
}
